/**
 * 在各个Action中使用
 */
export default {

  THEME_CHANGE:'THEME_CHANGE',
  THEME_INIT:'THEME_INIT',
  POP_REFRESH:'POP_REFRESH',
  POP_LOAD_FAIL:'POP_LOAD_FAIL',
  POP_LOAD_SUCCESS:'POP_LOAD_SUCCESS',
  POP_LOAD_MORE_SUCCESS:'POP_LOAD_MORE_SUCCESS',
  POP_LOAD_MORE_FAIL:'POP_LOAD_MORE_FAIL',
  POP_REF_FAV:'POP_REF_FAV',
  TRD_REFRESH:'TRD_REFRESH',
  TRD_LOAD_FAIL:'TRD_LOAD_FAIL',
  TRD_LOAD_SUCCESS:'TRD_LOAD_SUCCESS',
  TRD_LOAD_MORE_SUCCESS:'TRD_LOAD_MORE_SUCCESS',
  TRD_LOAD_MORE_FAIL:'TRD_LOAD_MORE_FAIL',
  TRD_REF_FAV:'TRD_REF_FAV',
  FAV_REFRESH:'FAV_REFRESH',
  FAV_LOAD_FAIL:'FAV_LOAD_FAIL',
  FAV_LOAD_SUCCESS:'FAV_LOAD_SUCCESS',
}